ECFMP/flow

.github/workflows/test.yml
=> ci: remove double configure php block

app/Models/DivisionDiscordWebhook.php, app/Models/FlightInformationRegion.php, database/factories/DivisionDiscordWebhookFactory.php, database/migrations/2022_06_30_174947_create_division_discord_webhooks_table.php, database/migrations/2022_06_30_182456_create_division_discord_webhook_flight_information_region_table.php
Just the structure for now so Kieran can start setting up database things.
=> feat: database structure for division discord webhooks

app/Filament/Resources/FlowMeasureResource.php
=> fix(FlowMeasureResource): fix active events not showing up

app/Filament/Resources/AirportGroupResource/RelationManagers/AirportsRelationManager.php, app/Filament/Resources/AirportResource/RelationManagers/GroupsRelationManager.php, app/Filament/Resources/FlightInformationRegionResource.php, app/Filament/Resources/FlightInformationRegionResource/RelationManagers/DiscordTagsRelationManager.php, app/Filament/Resources/FlightInformationRegionResource/RelationManagers/EventsRelationManager.php, app/Filament/Resources/FlightInformationRegionResource/RelationManagers/UsersRelationManager.php, app/Filament/Resources/UserResource/RelationManagers/FlightInformationRegionsRelationManager.php
=> fix: change to new relation manager

resources/views/filament/pages/user-guide/markdown-parser.blade.php
=> fix: fix typography not using full width

app/Filament/Resources/FlowMeasureResource.php, app/Filament/Resources/FlowMeasureResource/Pages/CreateFlowMeasure.php
=> fix(FlowMeasureResource): force start time to now if needed

app/Discord/FlowMeasure/Embed/ExpiredEmbeds.php, app/Discord/FlowMeasure/Embed/WithdrawnEmbeds.php, tests/Discord/FlowMeasure/Embed/ExpiredEmbedsTest.php, tests/Discord/FlowMeasure/Embed/WithdrawnEmbedsTest.php
=> feat: include optional filters in expired and withdrawn discord messages

app/Discord/FlowMeasure/Content/EcfmpInterestedParties.php, tests/Discord/FlowMeasure/Content/EcfmpInterestedPartiesTest.php
=> fix: send unique tags to ecfmp discord

app/Discord/FlowMeasure/Field/FormatsAirports.php, tests/Discord/FlowMeasure/Embed/ActivatedEmbedsTest.php, tests/Discord/FlowMeasure/Embed/ExpiredEmbedsTest.php, tests/Discord/FlowMeasure/Embed/NotifiedEmbedsTest.php, tests/Discord/FlowMeasure/Embed/WithdrawnEmbedsTest.php, tests/Discord/FlowMeasure/Field/ArrivalAirportsTest.php, tests/Discord/FlowMeasure/Field/DepartureAirportsTest.php
=> fix: escaped wildcard characters on departure airports

app/Filament/Resources/FlowMeasureResource.php
=> fix(FlowMeasureResource): changes for value

app/Filament/Resources/UserResource.php
=> feat(UserResource): enable search

app/Models/User.php
=> fix(UserResource): allow EVENT_MANAGER to be chosen by NMT

spec/api-spec-v1.json
=> docs(api): api docs url

app/Filament/Resources/FlowMeasureResource.php, app/Filament/Resources/FlowMeasureResource/Pages/EditFlowMeasure.php, app/Filament/Resources/FlowMeasureResource/Pages/ListFlowMeasures.php, app/Filament/Resources/FlowMeasureResource/Pages/ViewFlowMeasure.php, app/Filament/Resources/FlowMeasureResource/Traits/Filters.php, config/filament.php
Also re-generated `FlowMeasureResource` and friends for later.
=> fix(FlowMeasureResource): eager load airports

app/Filament/Resources/FlightInformationRegionResource.php
=> fix(FlightInformationRegionResource): ignore current record identifier

app/Policies/EventPolicy.php
=> fix(EventPolicy): fix permissions for event crud

app/Console/Kernel.php, app/Discord/FlowMeasure/Content/FlowMeasureRecipientsFactory.php, app/Filament/Resources/ActivityResource.php, app/Http/Controllers/EventController.php, app/Imports/EventParticipantsImport.php, database/factories/EventFactory.php, tests/Api/EventTest.php
=> feat(ActivityResource): add link to user

.github/workflows/lint.yml, app/Console/Kernel.php, app/Discord/FlowMeasure/Content/FlowMeasureRecipientsFactory.php, app/Http/Controllers/EventController.php, app/Imports/EventParticipantsImport.php, database/factories/EventFactory.php, tests/Api/EventTest.php
This makes sure code is styled according to PSR12
=> ci(lint): run pint on pr with test mode

app/Filament/Resources/FlightInformationRegionResource/RelationManagers/EventsRelationManager.php
FIR - events doesn't need them
=> fix(FlightInfornationRegionResource): remove associate actions

app/Filament/Resources/FlowMeasureResource/Pages/CreateFlowMeasure.php
=> fix(FlowMeasureResource): only trigger modal for specific measure types

app/Filament/Resources/FlowMeasureResource.php, app/Filament/Resources/FlowMeasureResource/Pages/CreateFlowMeasure.php, app/Filament/Resources/FlowMeasureResource/Pages/EditFlowMeasure.php, app/Filament/Resources/FlowMeasureResource/Pages/ViewFlowMeasure.php
=> fix(FlowMeasureResource): fix mandatory_route being broken

app/Discord/FlowMeasure/Webhook/Filter/ExpiredWebhookFilter.php, app/Helpers/FlowMeasureIdentifierGenerator.php, app/Models/FlowMeasure.php, app/Repository/FlowMeasureRepository.php, database/factories/FlowMeasureFactory.php, database/migrations/2022_08_18_162121_add_index_to_discord_notifications_table.php, tests/Discord/FlowMeasure/Webhook/Filter/ExpiredWebhookFilterTest.php, tests/Helpers/FlowMeasureIdentifierGeneratorTest.php, tests/Repository/FlowMeasureRepositoryTest.php
=> feat: expired flow measures

app/Filament/Resources/EventResource.php
=> fix: display events fir properly for non-editors

app/Console/Commands/ImportAirports.php, app/Filament/Resources/DivisionDiscordWebhookResource.php, app/Filament/Resources/DivisionDiscordWebhookResource/Pages/CreateDivisionDiscordWebhook.php, app/Filament/Resources/DivisionDiscordWebhookResource/Pages/EditDivisionDiscordWebhook.php, app/Filament/Resources/DivisionDiscordWebhookResource/Pages/ListDivisionDiscordWebhooks.php, app/Filament/Resources/DivisionDiscordWebhookResource/RelationManagers/FlightinformationregionsRelationManager.php, app/Policies/DivisionDiscordWebhookPolicy.php, app/Providers/AuthServiceProvider.php, composer.lock, tests/Feature/Filament/DivisionDiscordWebhookResource/FlightInformationRegionRelationManagerTest.php, tests/Feature/Filament/DivisionDiscordWebhookResourceTest.php
Allows NMT/System users to administer divisions discord webhooks and link them to FIRs
=> Division discord webhooks admin

app/Filament/Resources/FlightInformationRegionResource/RelationManagers/DiscordTagsRelationManager.php
=> fix: allow discord tags to be searchable by description

app/Jobs/SendDiscordNotifications.php, app/Jobs/UpdateNetworkData.php
=> fix: unique discord job
